import puppeteer from 'puppeteer';
import { Inspection, Client, Property, Finding, Category } from '@inspectavision/database';

export async function generateInspectionPDF(
  inspection: any,
  findings: any[]
): Promise<Buffer> {
  const browser = await puppeteer.launch({ headless: true });
  const page = await browser.newPage();

  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <style>
        body { font-family: 'Helvetica', sans-serif; color: #333; line-height: 1.6; }
        .header { text-align: center; padding: 40px; background: #f8f9fa; border-bottom: 5px solid #2563eb; }
        .report-title { font-size: 32px; font-weight: bold; margin-bottom: 10px; color: #1e40af; }
        .section { padding: 30px 50px; page-break-inside: avoid; }
        .section-title { font-size: 24px; border-bottom: 2px solid #e5e7eb; padding-bottom: 10px; margin-bottom: 20px; color: #1e3a8a; }
        .finding { margin-bottom: 30px; border: 1px solid #e5e7eb; border-radius: 8px; overflow: hidden; }
        .finding-header { background: #f3f4f6; padding: 15px; display: flex; justify-content: space-between; font-weight: bold; }
        .finding-body { padding: 15px; }
        .severity-maintenance { color: #d97706; }
        .severity-major { color: #dc2626; font-weight: bold; }
        .severity-safety { color: #991b1b; text-transform: uppercase; }
        .recommendation { margin-top: 10px; font-style: italic; color: #4b5563; border-left: 3px solid #2563eb; padding-left: 10px; }
        .standard-ref { margin-top: 10px; font-size: 12px; color: #9ca3af; }
        .footer { text-align: center; font-size: 12px; color: #6b7280; padding: 20px; border-top: 1px solid #e5e7eb; }
      </style>
    </head>
    <body>
      <div class="header">
        <div class="report-title">Inspection Report</div>
        <div>${inspection.property.address}</div>
        <div style="margin-top: 10px; color: #6b7280;">Date: ${new Date(inspection.scheduledAt).toLocaleDateString()}</div>
      </div>

      <div class="section">
        <div class="section-title">Client Information</div>
        <p><strong>Name:</strong> ${inspection.client.name}</p>
        <p><strong>Email:</strong> ${inspection.client.email}</p>
      </div>

      <div class="section">
        <div class="section-title">Findings by Category</div>
        ${findings.length === 0 ? '<p>No significant findings reported.</p>' : ''}
        
        ${findings.map(f => `
          <div class="finding">
            <div class="finding-header">
              <span>${f.location || 'General Location'}</span>
              <span class="severity-${f.severity}">${f.severity.toUpperCase()}</span>
            </div>
            <div class="finding-body">
              <p>${f.description}</p>
              <div class="recommendation"><strong>Recommendation:</strong> ${f.recommendation}</div>
              <div class="standard-ref">InterNACHI Reference: ${f.internachiReference}</div>
            </div>
          </div>
        `).join('')}
      </div>

      <div class="footer">
        Generated by Inspectavision AI - Professional Home Inspection Software
      </div>
    </body>
    </html>
  `;

  await page.setContent(htmlContent, { waitUntil: 'networkidle0' });
  const pdfBuffer = await page.pdf({ format: 'A4', printBackground: true });

  await browser.close();
  return Buffer.from(pdfBuffer);
}
