#!/bin/bash

# InspectaVision Android Setup Script
# This script helps set up the Android development environment

set -e

echo "🔧 InspectaVision Android Setup"
echo "================================"
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check for required tools
check_prerequisites() {
    echo "📋 Checking prerequisites..."
    
    # Check Java
    if command -v java &> /dev/null; then
        JAVA_VERSION=$(java -version 2>&1 | head -n 1 | cut -d'"' -f2 | cut -d'.' -f1)
        echo -e "${GREEN}✓${NC} Java found: $(java -version 2>&1 | head -n 1)"
        if [ "$JAVA_VERSION" -lt 17 ]; then
            echo -e "${RED}✗${NC} Java 17+ required, found: $JAVA_VERSION"
            exit 1
        fi
    else
        echo -e "${RED}✗${NC} Java not found. Please install JDK 17+"
        exit 1
    fi
    
    # Check Android SDK
    if [ -n "$ANDROID_HOME" ]; then
        echo -e "${GREEN}✓${NC} ANDROID_HOME: $ANDROID_HOME"
    else
        echo -e "${YELLOW}⚠${NC} ANDROID_HOME not set"
    fi
    
    # Check Android NDK
    if [ -n "$ANDROID_NDK_HOME" ]; then
        echo -e "${GREEN}✓${NC} ANDROID_NDK_HOME: $ANDROID_NDK_HOME"
    else
        echo -e "${YELLOW}⚠${NC} ANDROID_NDK_HOME not set (will use default)"
    fi
    
    echo ""
}

# Clone llama.cpp submodule
clone_llama_cpp() {
    echo "📦 Setting up llama.cpp..."
    
    LLAMA_CPP_DIR="apps/android/app/src/main/cpp/llama.cpp"
    
    if [ -d "$LLAMA_CPP_DIR" ]; then
        echo -e "${GREEN}✓${NC} llama.cpp already exists"
        echo "   Updating submodule..."
        cd "$LLAMA_CPP_DIR" && git pull && cd - > /dev/null
    else
        echo "   Cloning llama.cpp (branch b4426)..."
        mkdir -p "$(dirname "$LLAMA_CPP_DIR")"
        git clone --depth 1 --branch b4426 https://github.com/ggerganov/llama.cpp.git "$LLAMA_CPP_DIR"
    fi
    
    echo -e "${GREEN}✓${NC} llama.cpp setup complete"
    echo ""
}

# Set up local.properties
setup_local_properties() {
    echo "⚙️  Creating local.properties..."
    
    LOCAL_PROPS="apps/android/local.properties"
    
    cat > "$LOCAL_PROPS" << EOF
# Auto-generated by setup-android.sh
# Do not commit this file to version control

sdk.dir=${ANDROID_HOME:-$HOME/Android/Sdk}
ndk.dir=${ANDROID_NDK_HOME:-$HOME/Android/Sdk/ndk/26.1.10909125}
cmake.dir=${ANDROID_HOME:-$HOME/Android/Sdk}/cmake/3.22.1
EOF
    
    echo -e "${GREEN}✓${NC} local.properties created"
    echo ""
}

# Make gradlew executable
setup_gradle() {
    echo "🔨 Setting up Gradle wrapper..."
    
    chmod +x apps/android/gradlew
    echo -e "${GREEN}✓${NC} gradlew is now executable"
    echo ""
}

# Download sample model info
download_model_info() {
    echo "📚 Model recommendations..."
    echo ""
    echo "Download GGUF models from Hugging Face:"
    echo "  • Llama-3.2-1B-Instruct-GGUF"
    echo "  • Phi-3-mini-4k-instruct-GGUF"
    echo "  • Qwen2.5-1.5B-Instruct-GGUF"
    echo ""
    echo "Place models in:"
    echo "  /sdcard/models/"
    echo "  /sdcard/Download/models/"
    echo ""
}

# Main setup
main() {
    check_prerequisites
    clone_llama_cpp
    setup_local_properties
    setup_gradle
    download_model_info
    
    echo "================================"
    echo -e "${GREEN}✓${NC} Setup complete!"
    echo ""
    echo "Next steps:"
    echo "  1. Open Android Studio and import apps/android/"
    echo "  2. Or build from command line:"
    echo "     cd apps/android && ./gradlew assembleDebug"
    echo ""
    echo "  3. Install on device:"
    echo "     ./gradlew installDebug"
    echo ""
}

# Run main function
main "$@"
